export const hairProducts = [
  // Cleansing Products
  {
    id: "c1",
    name: "Sulfate-free Shampoo",
    price: 189.99,
    onSale: true,
    salePrice: 149.99,
    category: "Cleansing Products",
    image: "placeholder",
  },
  {
    id: "c2",
    name: "Clarifying Shampoo",
    price: 165.99,
    onSale: false,
    category: "Cleansing Products",
    image: "placeholder",
  },
  {
    id: "c3",
    name: "Co-wash Cleansing Conditioner",
    price: 210.99,
    onSale: false,
    category: "Cleansing Products",
    image: "placeholder",
  },

  // Conditioning Products
  {
    id: "d1",
    name: "Deep Conditioner",
    price: 249.99,
    onSale: true,
    salePrice: 199.99,
    category: "Conditioning Products",
    image: "placeholder",
  },
  {
    id: "d2",
    name: "Leave-in Conditioner",
    price: 179.99,
    onSale: false,
    category: "Conditioning Products",
    image: "placeholder",
  },
  {
    id: "d3",
    name: "Protein Treatment",
    price: 299.99,
    onSale: true,
    salePrice: 249.99,
    category: "Conditioning Products",
    image: "placeholder",
  },
  {
    id: "d4",
    name: "Hair Mask",
    price: 225.99,
    onSale: false,
    category: "Conditioning Products",
    image: "placeholder",
  },

  // Moisturizing & Styling Products
  {
    id: "m1",
    name: "Multi-Oil Hair Blend",
    price: 289.99,
    onSale: true,
    salePrice: 229.99,
    category: "Moisturizing & Styling Products",
    image: "placeholder",
  },
  {
    id: "m2",
    name: "Natural Hair Butter Blend",
    price: 199.99,
    onSale: false,
    category: "Moisturizing & Styling Products",
    image: "placeholder",
  },
  {
    id: "m3",
    name: "Moisturizing Hair Lotion",
    price: 159.99,
    onSale: false,
    category: "Moisturizing & Styling Products",
    image: "placeholder",
  },
  {
    id: "m4",
    name: "Curl Activator Cream",
    price: 179.99,
    onSale: true,
    salePrice: 149.99,
    category: "Moisturizing & Styling Products",
    image: "placeholder",
  },
  {
    id: "m5",
    name: "Alcohol-free Styling Gel",
    price: 145.99,
    onSale: false,
    category: "Moisturizing & Styling Products",
    image: "placeholder",
  },
  {
    id: "m6",
    name: "Volumizing Mousse",
    price: 169.99,
    onSale: true,
    salePrice: 139.99,
    category: "Moisturizing & Styling Products",
    image: "placeholder",
  },
  {
    id: "m7",
    name: "Edge Control Gel",
    price: 129.99,
    onSale: false,
    category: "Moisturizing & Styling Products",
    image: "placeholder",
  },

  // Tools & Accessories
  {
    id: "t1",
    name: "Professional Wide-tooth Comb",
    price: 89.99,
    onSale: false,
    category: "Tools & Accessories",
    image: "placeholder",
  },
  {
    id: "t2",
    name: "Detangling Brush",
    price: 159.99,
    onSale: true,
    salePrice: 129.99,
    category: "Tools & Accessories",
    image: "placeholder",
  },
  {
    id: "t3",
    name: "Mist Spray Bottle",
    price: 79.99,
    onSale: false,
    category: "Tools & Accessories",
    image: "placeholder",
  },
  {
    id: "t4",
    name: "Luxury Satin Bonnet",
    price: 199.99,
    onSale: true,
    salePrice: 169.99,
    category: "Tools & Accessories",
    image: "placeholder",
  },
  {
    id: "t5",
    name: "Silk Pillowcase",
    price: 299.99,
    onSale: false,
    category: "Tools & Accessories",
    image: "placeholder",
  },
  {
    id: "t6",
    name: "Sectioning Hair Clips Set",
    price: 119.99,
    onSale: true,
    salePrice: 99.99,
    category: "Tools & Accessories",
    image: "placeholder",
  },
];
